color:
  theme: custom

icons:
  # When "classic" is set, this is set to "never".
  # Possible values: always, auto, never
  when: never
  # Which icon theme to use.
  # Possible values: fancy, unicode
  theme: fancy
